name: Build Apk

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build Apk
    runs-on: windows-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v2

      - name: Setup Flutter
        uses: subosito/flutter-action@v2

      - name: Get Dependencies
        run: flutter pub get

      - name: Build APK COMMAND
        run: flutter build apk --release

      - name: Upload Apk
        uses: actions/upload-artifact@v2
        with:
          name: app-release
          path: build/app/outputs/flutter-apk/app-release.apk
