name: Build Apk

on:
  push: 
   branches:
    - master

jobs: 
  build:
    name: Build Apk
    runs-on: ubuntu-latest


    steps:
     - name: Checkout Code
        uses: actions/checkout@v4
      
     - name: Steup Flutter
        uses: subosito/flutter-action@v4
        with:
            flutter-version: '3.13.1'
      
     - name: Get Dependencies
        run: flutter pub get

     - name: Build APK COMMAND
       run: flutter build apk --relase

     - name: Upload Apk
       uses: actions/upload-artifact@v2
       with:
         name: app-release
         path: build/app/outputs/flutter-apk/app-release.apk
        


